---
title: Blog de Luis Enriquez
timezone: America/Halifax
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Este es un espacio creado desde la Habana Cuba, para hablar sobre temas
  de comunicación.

'
permalink: ":title/"
baseurl: "/"
url: 
author: Luis Enriquez
author-img: luis-enriquez-2016.jpg
about-author: Comunicador social, periodista, amante del software libre,  la tecnología
  y las redes sociales.
twitter: benetluis
linkedin: luisenriquezb
email: 
discus-identifier: 
analytics: gtag('config', 'UA-77725955-2');
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-paginate
paginate: 8
paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
gems:
- jekyll
- sitemap
- jekyll-feed
